import type { ComponentItem } from "@/storybook/components.generated";

export const STORYBOOK = {
  brand: {
    title: "One For All",
    subtitle: "Design system • Storybook-style",
  },
  navigation: {
    heading: "Sections",
    groups: [
      {
        id: "background",
        label: "Background",
        keywords: [
          "background",
          "bg",
          "gradient",
          "mesh",
          "noise",
          "pattern",
          "grid",
          "spotlight",
          "particles",
          "galaxy",
          "lightning",
          "vortex",
        ],
      },
      {
        id: "text",
        label: "Text",
        keywords: [
          "text",
          "typography",
          "font",
          "headline",
          "title",
          "split",
          "circular",
          "shiny",
          "highlight",
          "underline",
          "typewriter",
          "marquee",
          "glitch",
          "decrypted",
        ],
      },
      {
        id: "scroll",
        label: "Scroll",
        keywords: [
          "scroll",
          "parallax",
          "reveal",
          "velocity",
          "stack",
          "progress",
          "hero parallax",
        ],
      },
      {
        id: "cursor",
        label: "Cursor",
        keywords: ["cursor", "target", "ghost", "trail", "magnet"],
      },
      {
        id: "buttons",
        label: "Buttons",
        keywords: ["button", "cta", "toggle", "switch", "chip", "pill"],
      },
      {
        id: "forms",
        label: "Forms",
        keywords: [
          "form",
          "input",
          "select",
          "checkbox",
          "radio",
          "textarea",
          "slider",
          "range",
          "date",
          "otp",
          "field",
          "password",
          "combobox",
          "dropzone",
          "color picker",
        ],
      },
      {
        id: "navigation",
        label: "Navigation",
        keywords: [
          "nav",
          "navbar",
          "sidebar",
          "menu",
          "breadcrumb",
          "tabs",
          "pagination",
          "stepper",
          "dock",
          "file tree",
        ],
      },
      {
        id: "layout",
        label: "Layout",
        keywords: [
          "layout",
          "container",
          "section",
          "grid",
          "flex",
          "card",
          "accordion",
          "collapse",
          "panel",
          "stack",
          "bento",
          "masonry",
        ],
      },
      {
        id: "data",
        label: "Data",
        keywords: [
          "table",
          "chart",
          "badge",
          "tag",
          "avatar",
          "progress",
          "timeline",
          "stat",
          "metric",
          "list",
          "kanban",
          "gantt",
          "calendar",
          "qr",
        ],
      },
      {
        id: "charts",
        label: "Charts",
        keywords: ["area", "bar", "pie", "donut", "radar", "chart"],
      },
      {
        id: "media",
        label: "Media",
        keywords: ["video", "player", "image", "zoom", "crop", "compare"],
      },
      {
        id: "three-d",
        label: "3D",
        keywords: ["3d", "sphere", "lanyard", "model"],
      },
      {
        id: "feedback",
        label: "Feedback",
        keywords: [
          "toast",
          "modal",
          "dialog",
          "tooltip",
          "popover",
          "alert",
          "notification",
          "drawer",
          "sheet",
        ],
      },
      {
        id: "effects",
        label: "Effects",
        keywords: [
          "glow",
          "shadow",
          "blur",
          "shimmer",
          "skeleton",
          "sparkle",
          "animation",
          "hover",
          "parallax",
          "beam",
          "confetti",
          "fireworks",
          "meteors",
        ],
      },
      {
        id: "other",
        label: "Other",
        keywords: [],
      },
    ],
  },
  search: {
    placeholder: "Search components, tokens, docs…",
    shortcutLabel: "Ctrl K",
  },
  componentPage: {
    tabs: { preview: "Preview", code: "Code" },
    previewTitle: "Demo",
    installTitle: "Installation",
    installHint: "Open the upstream docs to see the original API + examples.",
    customizeTitle: "Customize",
    customizeHint: "Adjust the local demo wrapper to preview styling changes.",
    apiTitle: "API References",
  },
  demo: {
    installCommand: (component: ComponentItem) => component.url,
    controls: {
      radius: { label: "Radius", min: 8, max: 24, default: 14 },
      padding: { label: "Padding", min: 12, max: 40, default: 24 },
      glow: { label: "Glow", min: 0, max: 24, default: 0 },
    },
    apiRows: [
      {
        prop: "radius",
        type: "number",
        default: "14",
        description: "Card corner radius",
      },
      {
        prop: "padding",
        type: "number",
        default: "24",
        description: "Card inner padding",
      },
      {
        prop: "glow",
        type: "number",
        default: "0",
        description: "Accent glow intensity",
      },
    ],
  },
} as const;
