import { DemoControl } from "../types";

export const controls: DemoControl[] = [
      {
        type: "text",
        param: "imageSrc",
        label: "Image Source",
        defaultValue:
          "https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=500&auto=format&fit=crop&q=60",
      },
      {
        type: "number",
        param: "width",
        label: "Width (px)",
        defaultValue: 300,
        min: 100,
        max: 500,
        step: 10,
      },
      {
        type: "number",
        param: "rotate",
        label: "Rotate",
        defaultValue: 15,
        min: -180,
        max: 180,
        step: 1,
      },
      {
        type: "number",
        param: "peelBackHoverPct",
        label: "Hover Peel %",
        defaultValue: 30,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "number",
        param: "peelBackActivePct",
        label: "Active Peel %",
        defaultValue: 40,
        min: 0,
        max: 100,
        step: 1,
      },
      {
        type: "number",
        param: "peelDirection",
        label: "Direction",
        defaultValue: 0,
        min: 0,
        max: 360,
        step: 1,
      },
      {
        type: "number",
        param: "shadowIntensity",
        label: "Shadow",
        defaultValue: 0.6,
        min: 0,
        max: 1,
        step: 0.1,
      },
      {
        type: "number",
        param: "lightingIntensity",
        label: "Lighting",
        defaultValue: 0.1,
        min: 0,
        max: 1,
        step: 0.05,
      },
    ];