// This file is auto-generated by scripts/generate-components-data.mjs
// Do not edit by hand.

export type ComponentRegistryItem = {
  id: string;
  order: number;
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: readonly string[];
  library: string;
  docUrl: string;
  installCommand: string;
};

export const COMPONENTS: ComponentRegistryItem[] = [
  {
    "id": "1",
    "order": 1,
    "slug": "split-text",
    "title": "Split Text",
    "description": "Splits a heading into segments so you can animate parts independently.",
    "category": "Text",
    "tags": [
      "split",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/split-text",
    "installCommand": ""
  },
  {
    "id": "2",
    "order": 2,
    "slug": "circular-text",
    "title": "Circular Text",
    "description": "Renders text around a circle for badges, stamps, and hero accents.",
    "category": "Text",
    "tags": [
      "circular",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/circular-text",
    "installCommand": ""
  },
  {
    "id": "3",
    "order": 3,
    "slug": "shiny-text",
    "title": "Shiny Text",
    "description": "Adds a moving highlight / shimmer effect across text.",
    "category": "Text",
    "tags": [
      "shiny",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/shiny-text",
    "installCommand": ""
  },
  {
    "id": "4",
    "order": 4,
    "slug": "curved-marquee",
    "title": "Curved Marquee",
    "description": "Animated text effect: Curved Marquee.",
    "category": "Text",
    "tags": [
      "curved",
      "marquee",
      "text",
      "animations",
      "loop",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/curved-loop",
    "installCommand": ""
  },
  {
    "id": "5",
    "order": 5,
    "slug": "fuzzy-text",
    "title": "Fuzzy Text",
    "description": "Animated text effect: Fuzzy Text.",
    "category": "Text",
    "tags": [
      "fuzzy",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/fuzzy-text",
    "installCommand": ""
  },
  {
    "id": "6",
    "order": 6,
    "slug": "gradient-text",
    "title": "Gradient Text",
    "description": "Applies a multi-color gradient fill to text (great for headings).",
    "category": "Text",
    "tags": [
      "gradient",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/gradient-text",
    "installCommand": ""
  },
  {
    "id": "7",
    "order": 7,
    "slug": "falling-text",
    "title": "Falling Text",
    "description": "Animated text effect: Falling Text.",
    "category": "Text",
    "tags": [
      "falling",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/falling-text",
    "installCommand": ""
  },
  {
    "id": "8",
    "order": 8,
    "slug": "text-cursor",
    "title": "Text Cursor",
    "description": "Animated text effect: Text Cursor.",
    "category": "Text",
    "tags": [
      "text",
      "cursor",
      "animations",
      "react",
      "bits",
      "pointer"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/text-cursor",
    "installCommand": ""
  },
  {
    "id": "9",
    "order": 9,
    "slug": "decrypted-text",
    "title": "Decrypted Text",
    "description": "Reveals text by cycling through random characters (decryption effect).",
    "category": "Text",
    "tags": [
      "decrypted",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/decrypted-text",
    "installCommand": ""
  },
  {
    "id": "10",
    "order": 10,
    "slug": "scroll-float",
    "title": "Scroll Float",
    "description": "Gently offsets elements based on scroll position for depth.",
    "category": "Text",
    "tags": [
      "scroll",
      "float",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/scroll-float",
    "installCommand": ""
  },
  {
    "id": "11",
    "order": 11,
    "slug": "scroll-reveal",
    "title": "Scroll Reveal",
    "description": "Reveals content as it enters the viewport while scrolling.",
    "category": "Text",
    "tags": [
      "scroll",
      "reveal",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/scroll-reveal",
    "installCommand": ""
  },
  {
    "id": "12",
    "order": 12,
    "slug": "rotating-text",
    "title": "Rotating Text",
    "description": "Animated text effect: Rotating Text.",
    "category": "Text",
    "tags": [
      "rotating",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/rotating-text",
    "installCommand": ""
  },
  {
    "id": "13",
    "order": 13,
    "slug": "glitch-text",
    "title": "Glitch Text",
    "description": "Creates a glitchy, distorted text effect for cyber/retro styles.",
    "category": "Text",
    "tags": [
      "glitch",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/glitch-text",
    "installCommand": ""
  },
  {
    "id": "14",
    "order": 14,
    "slug": "scroll-velocity",
    "title": "Scroll Velocity",
    "description": "Animated text effect: Scroll Velocity.",
    "category": "Text",
    "tags": [
      "scroll",
      "velocity",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/scroll-velocity",
    "installCommand": ""
  },
  {
    "id": "15",
    "order": 15,
    "slug": "variable-proximity",
    "title": "Variable Proximity",
    "description": "Animated text effect: Variable Proximity.",
    "category": "Text",
    "tags": [
      "variable",
      "proximity",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/variable-proximity",
    "installCommand": ""
  },
  {
    "id": "16",
    "order": 16,
    "slug": "count-up",
    "title": "Count Up",
    "description": "Animates a number from 0 to a target value (stats/metrics).",
    "category": "Text",
    "tags": [
      "count",
      "up",
      "text",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/text-animations/count-up",
    "installCommand": ""
  },
  {
    "id": "17",
    "order": 17,
    "slug": "electric-border",
    "title": "Electric Border",
    "description": "Electric Border — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "electric",
      "border",
      "card"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/electric-border",
    "installCommand": ""
  },
  {
    "id": "18",
    "order": 18,
    "slug": "antigravity",
    "title": "Antigravity",
    "description": "Antigravity — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "antigravity",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/antigravity",
    "installCommand": ""
  },
  {
    "id": "19",
    "order": 19,
    "slug": "logo-loop",
    "title": "Logo Loop",
    "description": "Logo Loop — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "logo",
      "loop",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/logo-loop",
    "installCommand": ""
  },
  {
    "id": "20",
    "order": 20,
    "slug": "target-cursor",
    "title": "Target Cursor",
    "description": "Target Cursor — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "target",
      "cursor",
      "animations",
      "react",
      "bits",
      "pointer"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/target-cursor",
    "installCommand": ""
  },
  {
    "id": "21",
    "order": 21,
    "slug": "laser-flow",
    "title": "Laser Flow",
    "description": "Laser Flow — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "laser",
      "flow",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/laser-flow",
    "installCommand": ""
  },
  {
    "id": "22",
    "order": 22,
    "slug": "magnet-lines",
    "title": "Magnet Lines",
    "description": "Magnet Lines — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "magnet",
      "lines",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/magnet-lines",
    "installCommand": ""
  },
  {
    "id": "23",
    "order": 23,
    "slug": "ghost-cursor",
    "title": "Ghost Cursor",
    "description": "Ghost Cursor — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "ghost",
      "cursor",
      "animations",
      "react",
      "bits",
      "pointer"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/ghost-cursor",
    "installCommand": ""
  },
  {
    "id": "24",
    "order": 24,
    "slug": "click-spark",
    "title": "Click Spark",
    "description": "Click Spark — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "click",
      "spark",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/click-spark",
    "installCommand": ""
  },
  {
    "id": "25",
    "order": 25,
    "slug": "sticker-peel",
    "title": "Sticker Peel",
    "description": "Sticker Peel — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "sticker",
      "peel",
      "drag"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/sticker-peel",
    "installCommand": ""
  },
  {
    "id": "26",
    "order": 26,
    "slug": "image-trail",
    "title": "Image Trail",
    "description": "Image Trail — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "image",
      "trail",
      "animations",
      "imawge",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/imawge-trail",
    "installCommand": ""
  },
  {
    "id": "27",
    "order": 27,
    "slug": "splash-cursor",
    "title": "Splash Cursor",
    "description": "Splash Cursor — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "splash",
      "cursor",
      "animations",
      "react",
      "bits",
      "pointer"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/splash-cursor",
    "installCommand": ""
  },
  {
    "id": "28",
    "order": 28,
    "slug": "star-border",
    "title": "Star Border",
    "description": "Star Border — a UI component reference from React-Bits.",
    "category": "Animations",
    "tags": [
      "star",
      "border",
      "animations",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/animations/star-border",
    "installCommand": ""
  },
  {
    "id": "29",
    "order": 29,
    "slug": "animated-list",
    "title": "Animated List",
    "description": "Animated List — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "animated",
      "list",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/animated-list",
    "installCommand": ""
  },
  {
    "id": "30",
    "order": 30,
    "slug": "scroll-stack",
    "title": "Scroll Stack",
    "description": "Scroll Stack — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "scroll",
      "stack",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/scroll-stack",
    "installCommand": ""
  },
  {
    "id": "31",
    "order": 31,
    "slug": "magic-bento",
    "title": "Magic Bento",
    "description": "Magic Bento — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "magic",
      "bento",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/magic-bento",
    "installCommand": ""
  },
  {
    "id": "32",
    "order": 32,
    "slug": "circular-gallery",
    "title": "Circular Gallery",
    "description": "Circular Gallery — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "circular",
      "gallery",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/circular-gallery",
    "installCommand": ""
  },
  {
    "id": "33",
    "order": 33,
    "slug": "image-stack",
    "title": "Image Stack",
    "description": "Image Stack — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "image",
      "stack",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/stack",
    "installCommand": ""
  },
  {
    "id": "34",
    "order": 34,
    "slug": "fluid-glass",
    "title": "Fluid Glass",
    "description": "Fluid Glass — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "fluid",
      "glass",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/fluid-glass",
    "installCommand": ""
  },
  {
    "id": "35",
    "order": 35,
    "slug": "masonry",
    "title": "Masonry",
    "description": "Masonry — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "masonry",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/masonry",
    "installCommand": ""
  },
  {
    "id": "36",
    "order": 36,
    "slug": "modal-viewer",
    "title": "Modal Viewer",
    "description": "Modal Viewer — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "modal",
      "viewer",
      "model",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/model-viewer",
    "installCommand": ""
  },
  {
    "id": "37",
    "order": 37,
    "slug": "lanyard",
    "title": "Lanyard",
    "description": "Lanyard — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "lanyard",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/lanyard",
    "installCommand": ""
  },
  {
    "id": "38",
    "order": 38,
    "slug": "dock",
    "title": "Dock",
    "description": "Dock — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "dock",
      "navigation",
      "toolbar"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/dock",
    "installCommand": ""
  },
  {
    "id": "39",
    "order": 39,
    "slug": "carousel",
    "title": "Carousel",
    "description": "Carousel — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "carousel",
      "react",
      "bits",
      "slider"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/carousel",
    "installCommand": ""
  },
  {
    "id": "40",
    "order": 40,
    "slug": "spotlight-card",
    "title": "Spotlight Card",
    "description": "Spotlight Card — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "spotlight",
      "card",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/spotlight-card",
    "installCommand": ""
  },
  {
    "id": "41",
    "order": 41,
    "slug": "flowing-menu",
    "title": "Flowing Menu",
    "description": "Navigation component: Flowing Menu.",
    "category": "Components",
    "tags": [
      "flowing",
      "menu",
      "react",
      "bits",
      "navigation"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/flowing-menu",
    "installCommand": ""
  },
  {
    "id": "42",
    "order": 42,
    "slug": "elastic-slider",
    "title": "Elastic Slider",
    "description": "Elastic Slider — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "elastic",
      "slider",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/elastic-slider",
    "installCommand": ""
  },
  {
    "id": "43",
    "order": 43,
    "slug": "counter",
    "title": "Counter",
    "description": "Animates a number from 0 to a target value (stats/metrics).",
    "category": "Components",
    "tags": [
      "counter",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/counter",
    "installCommand": ""
  },
  {
    "id": "44",
    "order": 44,
    "slug": "infinite-menu",
    "title": "Infinite Menu",
    "description": "Navigation component: Infinite Menu.",
    "category": "Components",
    "tags": [
      "infinite",
      "menu",
      "react",
      "bits",
      "navigation"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/infinite-menu",
    "installCommand": ""
  },
  {
    "id": "45",
    "order": 45,
    "slug": "stepper",
    "title": "Stepper",
    "description": "Stepper — a UI component reference from React-Bits.",
    "category": "Components",
    "tags": [
      "stepper",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/components/stepper",
    "installCommand": ""
  },
  {
    "id": "46",
    "order": 46,
    "slug": "liquid-ether",
    "title": "Liquid Ether",
    "description": "Animated background preset: Liquid Ether (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "liquid",
      "ether",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/liquid-ether",
    "installCommand": ""
  },
  {
    "id": "47",
    "order": 47,
    "slug": "prism",
    "title": "Prism",
    "description": "Animated background preset: Prism (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "prism",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/prism",
    "installCommand": ""
  },
  {
    "id": "48",
    "order": 48,
    "slug": "dark-veil",
    "title": "Dark Veil",
    "description": "Animated background preset: Dark Veil (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "dark",
      "veil",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/dark-veil",
    "installCommand": ""
  },
  {
    "id": "49",
    "order": 49,
    "slug": "light-pillar",
    "title": "Light Pillar",
    "description": "Animated background preset: Light Pillar (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "light",
      "pillar",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/light-pillar",
    "installCommand": ""
  },
  {
    "id": "50",
    "order": 50,
    "slug": "floating-lines",
    "title": "Floating Lines",
    "description": "Animated background preset: Floating Lines (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "floating",
      "lines",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/floating-lines",
    "installCommand": ""
  },
  {
    "id": "51",
    "order": 51,
    "slug": "light-rays",
    "title": "Light Rays",
    "description": "Animated background preset: Light Rays (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "light",
      "rays",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/light-rays",
    "installCommand": ""
  },
  {
    "id": "52",
    "order": 52,
    "slug": "color-bends",
    "title": "Color Bends",
    "description": "Animated background preset: Color Bends (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "color",
      "bends",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/color-bends",
    "installCommand": ""
  },
  {
    "id": "53",
    "order": 53,
    "slug": "particles",
    "title": "Particles",
    "description": "Animated background preset: Particles (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "particles",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/particles",
    "installCommand": ""
  },
  {
    "id": "54",
    "order": 54,
    "slug": "grid-scan",
    "title": "Grid Scan",
    "description": "Animated background preset: Grid Scan (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "grid",
      "scan",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/grid-scan",
    "installCommand": ""
  },
  {
    "id": "55",
    "order": 55,
    "slug": "lightning",
    "title": "Lightning",
    "description": "Animated background preset: Lightning (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "lightning",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/lightning",
    "installCommand": ""
  },
  {
    "id": "56",
    "order": 56,
    "slug": "galaxy",
    "title": "Galaxy",
    "description": "Animated background preset: Galaxy (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "galaxy",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/galaxy",
    "installCommand": ""
  },
  {
    "id": "57",
    "order": 57,
    "slug": "dot-grid",
    "title": "Dot Grid",
    "description": "Animated background preset: Dot Grid (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "dot",
      "grid",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/dot-grid",
    "installCommand": ""
  },
  {
    "id": "58",
    "order": 58,
    "slug": "hyperspeed",
    "title": "Hyperspeed",
    "description": "Animated background preset: Hyperspeed (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "hyperspeed",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/hyperspeed",
    "installCommand": ""
  },
  {
    "id": "59",
    "order": 59,
    "slug": "ballpit",
    "title": "Ballpit",
    "description": "Animated background preset: Ballpit (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "ballpit",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/ballpit",
    "installCommand": ""
  },
  {
    "id": "60",
    "order": 60,
    "slug": "orbs",
    "title": "Orbs",
    "description": "Animated background preset: Orbs (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "orbs",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/orbs",
    "installCommand": ""
  },
  {
    "id": "61",
    "order": 61,
    "slug": "letter-glitch",
    "title": "Letter Glitch",
    "description": "Creates a glitchy, distorted text effect for cyber/retro styles.",
    "category": "Background",
    "tags": [
      "letter",
      "glitch",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/letter-glitch",
    "installCommand": ""
  },
  {
    "id": "62",
    "order": 62,
    "slug": "grid-motion",
    "title": "Grid Motion",
    "description": "Animated background preset: Grid Motion (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "grid",
      "motion",
      "backgrounds",
      "react",
      "bits"
    ],
    "library": "React-Bits",
    "docUrl": "https://reactbits.dev/backgrounds/grid-motion",
    "installCommand": ""
  },
  {
    "id": "63",
    "order": 63,
    "slug": "code-block",
    "title": "Code Block",
    "description": "Code Block — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "code",
      "block",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/code-block",
    "installCommand": ""
  },
  {
    "id": "64",
    "order": 64,
    "slug": "code-editor",
    "title": "Code Editor",
    "description": "Code Editor — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "code",
      "editor",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/code-editor",
    "installCommand": ""
  },
  {
    "id": "65",
    "order": 65,
    "slug": "code-tabs",
    "title": "Code Tabs",
    "description": "Code Tabs — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "code",
      "tabs",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/code-tabs",
    "installCommand": ""
  },
  {
    "id": "66",
    "order": 66,
    "slug": "sandbox",
    "title": "Sandbox",
    "description": "Sandbox — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "sandbox",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/sandbox",
    "installCommand": ""
  },
  {
    "id": "67",
    "order": 67,
    "slug": "ganttchart",
    "title": "GanttChart",
    "description": "GanttChart — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "ganttchart",
      "gantt",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/gantt",
    "installCommand": ""
  },
  {
    "id": "68",
    "order": 68,
    "slug": "kanban",
    "title": "Kanban",
    "description": "Kanban — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "kanban",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/kanban",
    "installCommand": ""
  },
  {
    "id": "69",
    "order": 69,
    "slug": "device-mock",
    "title": "Device Mock(Android)",
    "description": "Device Mock(Android) — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "device",
      "mock",
      "android",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/android",
    "installCommand": ""
  },
  {
    "id": "70",
    "order": 70,
    "slug": "device-mock-2",
    "title": "Device Mock(IOS)",
    "description": "Device Mock(IOS) — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "device",
      "mock",
      "ios",
      "iphone",
      "15",
      "pro",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/iphone-15-pro",
    "installCommand": ""
  },
  {
    "id": "71",
    "order": 71,
    "slug": "macos-dock",
    "title": "MacOS Dock",
    "description": "MacOS Dock — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "macos",
      "dock",
      "mac",
      "os",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/mac-os-dock",
    "installCommand": ""
  },
  {
    "id": "72",
    "order": 72,
    "slug": "rating",
    "title": "Rating",
    "description": "Rating — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "rating",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/rating",
    "installCommand": ""
  },
  {
    "id": "73",
    "order": 73,
    "slug": "credit-card",
    "title": "Credit Card",
    "description": "Credit Card — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "credit",
      "card",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/credit-card",
    "installCommand": ""
  },
  {
    "id": "74",
    "order": 74,
    "slug": "color-picker",
    "title": "Color Picker",
    "description": "Color Picker — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "color",
      "picker",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/color-picker",
    "installCommand": ""
  },
  {
    "id": "75",
    "order": 75,
    "slug": "combobox",
    "title": "Combobox",
    "description": "Combobox — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "combobox",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/combobox",
    "installCommand": ""
  },
  {
    "id": "76",
    "order": 76,
    "slug": "dropzone",
    "title": "Dropzone",
    "description": "Dropzone — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "dropzone",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/dropzone",
    "installCommand": ""
  },
  {
    "id": "77",
    "order": 77,
    "slug": "image-zoom",
    "title": "Image Zoom",
    "description": "Image Zoom — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "image",
      "zoom",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/image-zoom",
    "installCommand": ""
  },
  {
    "id": "78",
    "order": 78,
    "slug": "image-crop",
    "title": "Image Crop",
    "description": "Image Crop — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "image",
      "crop",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/image-crop",
    "installCommand": ""
  },
  {
    "id": "79",
    "order": 79,
    "slug": "3d-card",
    "title": "3D Card",
    "description": "3D Card — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "3d",
      "card",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/3d-card",
    "installCommand": ""
  },
  {
    "id": "80",
    "order": 80,
    "slug": "3d-marquee",
    "title": "3D Marquee",
    "description": "3D Marquee — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "3d",
      "marquee",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/3d-marquee",
    "installCommand": ""
  },
  {
    "id": "81",
    "order": 81,
    "slug": "animated-cursor",
    "title": "Animated Cursor",
    "description": "Animated Cursor — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "animated",
      "cursor",
      "shadcn",
      "pointer"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/animated-cursor",
    "installCommand": ""
  },
  {
    "id": "82",
    "order": 82,
    "slug": "animated-testimonials",
    "title": "Animated Testimonials",
    "description": "Animated Testimonials — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "animated",
      "testimonials",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/animated-testimonials",
    "installCommand": ""
  },
  {
    "id": "83",
    "order": 83,
    "slug": "animated-tooltip",
    "title": "Animated Tooltip",
    "description": "Animated Tooltip — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "animated",
      "tooltip",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/animated-tooltip",
    "installCommand": ""
  },
  {
    "id": "84",
    "order": 84,
    "slug": "glimpse",
    "title": "Glimpse",
    "description": "Glimpse — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "glimpse",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/glimpse",
    "installCommand": ""
  },
  {
    "id": "85",
    "order": 85,
    "slug": "pin-list",
    "title": "Pin List",
    "description": "Pin List — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "pin",
      "list",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/pin-list",
    "installCommand": ""
  },
  {
    "id": "86",
    "order": 86,
    "slug": "spinner",
    "title": "Spinner",
    "description": "Spinner — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "spinner",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/spinner",
    "installCommand": ""
  },
  {
    "id": "87",
    "order": 87,
    "slug": "tabs",
    "title": "Tabs",
    "description": "Tabs — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "tabs",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/tabs",
    "installCommand": ""
  },
  {
    "id": "88",
    "order": 88,
    "slug": "banner",
    "title": "Banner",
    "description": "Banner — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "banner",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/banner",
    "installCommand": ""
  },
  {
    "id": "89",
    "order": 89,
    "slug": "marquee",
    "title": "Marquee",
    "description": "Marquee — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "marquee",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/marquee",
    "installCommand": ""
  },
  {
    "id": "90",
    "order": 90,
    "slug": "avatar-group",
    "title": "Avatar Group",
    "description": "Avatar Group — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "avatar",
      "group",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/avatar-group",
    "installCommand": ""
  },
  {
    "id": "91",
    "order": 91,
    "slug": "tags",
    "title": "Tags",
    "description": "Tags — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "tags",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/tags",
    "installCommand": ""
  },
  {
    "id": "92",
    "order": 92,
    "slug": "calendar",
    "title": "Calendar",
    "description": "Calendar — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "calendar",
      "date",
      "picker"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/calendar",
    "installCommand": ""
  },
  {
    "id": "93",
    "order": 93,
    "slug": "mini-calendar",
    "title": "Mini Calendar",
    "description": "Mini Calendar — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "mini",
      "calendar",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/mini-calendar",
    "installCommand": ""
  },
  {
    "id": "94",
    "order": 94,
    "slug": "comparison-slider",
    "title": "Comparison Slider",
    "description": "Comparison Slider — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "comparison",
      "slider",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/comparison",
    "installCommand": ""
  },
  {
    "id": "95",
    "order": 95,
    "slug": "kbd",
    "title": "KBD",
    "description": "KBD — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "kbd",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/kbd",
    "installCommand": ""
  },
  {
    "id": "96",
    "order": 96,
    "slug": "qr-code",
    "title": "Qr Code",
    "description": "Qr Code — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "qr",
      "code",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/qr-code",
    "installCommand": ""
  },
  {
    "id": "97",
    "order": 97,
    "slug": "status",
    "title": "Status",
    "description": "Status — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "status",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/status",
    "installCommand": ""
  },
  {
    "id": "98",
    "order": 98,
    "slug": "terminal",
    "title": "Terminal",
    "description": "Terminal — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "terminal",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/terminal",
    "installCommand": ""
  },
  {
    "id": "99",
    "order": 99,
    "slug": "video-player",
    "title": "Video Player",
    "description": "Video Player — a UI component reference from shadcn.",
    "category": "Components",
    "tags": [
      "video",
      "player",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/components/video-player",
    "installCommand": ""
  },
  {
    "id": "100",
    "order": 100,
    "slug": "beam-collision",
    "title": "Beam Collision",
    "description": "Animated background preset: Beam Collision (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "beam",
      "collision",
      "background",
      "beams",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/beams-collision",
    "installCommand": ""
  },
  {
    "id": "101",
    "order": 101,
    "slug": "confetti",
    "title": "Confetti",
    "description": "Animated background preset: Confetti (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "confetti",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/confetti",
    "installCommand": ""
  },
  {
    "id": "102",
    "order": 102,
    "slug": "fireworks",
    "title": "Fireworks",
    "description": "Animated background preset: Fireworks (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "fireworks",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/fireworks",
    "installCommand": ""
  },
  {
    "id": "103",
    "order": 103,
    "slug": "meteors",
    "title": "Meteors",
    "description": "Animated background preset: Meteors (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "meteors",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/meteors",
    "installCommand": ""
  },
  {
    "id": "104",
    "order": 104,
    "slug": "orbits",
    "title": "Orbits",
    "description": "Animated background preset: Orbits (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "orbits",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/orbits",
    "installCommand": ""
  },
  {
    "id": "105",
    "order": 105,
    "slug": "rain",
    "title": "Rain",
    "description": "Animated background preset: Rain (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "rain",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/rain",
    "installCommand": ""
  },
  {
    "id": "106",
    "order": 106,
    "slug": "snow",
    "title": "Snow",
    "description": "Animated background preset: Snow (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "snow",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/snow",
    "installCommand": ""
  },
  {
    "id": "107",
    "order": 107,
    "slug": "vortex",
    "title": "Vortex",
    "description": "Animated background preset: Vortex (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "vortex",
      "background",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/background/vortex",
    "installCommand": ""
  },
  {
    "id": "108",
    "order": 108,
    "slug": "gradient-area-chart",
    "title": "Gradient Area Chart",
    "description": "Chart component: Gradient Area Chart (data visualization).",
    "category": "Components",
    "tags": [
      "gradient",
      "area",
      "chart",
      "charts",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/charts/area-gradient",
    "installCommand": ""
  },
  {
    "id": "109",
    "order": 109,
    "slug": "horizontal-bar",
    "title": "Horizontal Bar",
    "description": "Chart component: Horizontal Bar (data visualization).",
    "category": "Components",
    "tags": [
      "horizontal",
      "bar",
      "charts",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/charts/bar-horizontal",
    "installCommand": ""
  },
  {
    "id": "110",
    "order": 110,
    "slug": "interactive-bar",
    "title": "Interactive Bar",
    "description": "Chart component: Interactive Bar (data visualization).",
    "category": "Components",
    "tags": [
      "interactive",
      "bar",
      "charts",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/charts/bar-interactive",
    "installCommand": ""
  },
  {
    "id": "111",
    "order": 111,
    "slug": "pie-donut",
    "title": "Pie Donut",
    "description": "Chart component: Pie Donut (data visualization).",
    "category": "Components",
    "tags": [
      "pie",
      "donut",
      "charts",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/charts/pie-donut",
    "installCommand": ""
  },
  {
    "id": "112",
    "order": 112,
    "slug": "radar-chart",
    "title": "Radar Chart",
    "description": "Chart component: Radar Chart (data visualization).",
    "category": "Components",
    "tags": [
      "radar",
      "chart",
      "charts",
      "dots",
      "shadcn"
    ],
    "library": "shadcn",
    "docUrl": "https://www.shadcn.io/charts/radar-dots",
    "installCommand": ""
  },
  {
    "id": "113",
    "order": 113,
    "slug": "rainbow-button",
    "title": "Rainbow button",
    "description": "Button/CTA component: Rainbow button.",
    "category": "Components",
    "tags": [
      "rainbow",
      "button",
      "docs",
      "buttons",
      "joly",
      "cta"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/buttons/rainbow-button",
    "installCommand": ""
  },
  {
    "id": "114",
    "order": 114,
    "slug": "gooey-text-morphing",
    "title": "Gooey Text Morphing",
    "description": "Animated text effect: Gooey Text Morphing.",
    "category": "Text",
    "tags": [
      "gooey",
      "text",
      "morphing",
      "docs",
      "animations",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/gooey-text-morphing",
    "installCommand": ""
  },
  {
    "id": "115",
    "order": 115,
    "slug": "highlight-text",
    "title": "Highlight Text",
    "description": "Animated text effect: Highlight Text.",
    "category": "Text",
    "tags": [
      "highlight",
      "text",
      "docs",
      "animations",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/highlight-text",
    "installCommand": ""
  },
  {
    "id": "116",
    "order": 116,
    "slug": "number-counter",
    "title": "Number Counter",
    "description": "Animates a number from 0 to a target value (stats/metrics).",
    "category": "Text",
    "tags": [
      "number",
      "counter",
      "docs",
      "text",
      "animations",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/number-counter",
    "installCommand": ""
  },
  {
    "id": "117",
    "order": 117,
    "slug": "rotate-text",
    "title": "Rotate Text",
    "description": "Animated text effect: Rotate Text.",
    "category": "Text",
    "tags": [
      "rotate",
      "text",
      "docs",
      "animations",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/rotate-text",
    "installCommand": ""
  },
  {
    "id": "118",
    "order": 118,
    "slug": "typewriter-text",
    "title": "Typewriter Text",
    "description": "Types text character-by-character with a blinking cursor.",
    "category": "Text",
    "tags": [
      "typewriter",
      "text",
      "docs",
      "animations",
      "typewritter",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/typewritter-text",
    "installCommand": ""
  },
  {
    "id": "119",
    "order": 119,
    "slug": "ai-prompt-box",
    "title": "AI prompt box",
    "description": "Input/form component: AI prompt box.",
    "category": "Components",
    "tags": [
      "ai",
      "prompt",
      "box",
      "docs",
      "inputs",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/ai-prompt-box",
    "installCommand": ""
  },
  {
    "id": "120",
    "order": 120,
    "slug": "animated-theme-toggle",
    "title": "Animated Theme Toggle",
    "description": "Input/form component: Animated Theme Toggle.",
    "category": "Components",
    "tags": [
      "animated",
      "theme",
      "toggle",
      "docs",
      "inputs",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/animated-theme-toggle",
    "installCommand": ""
  },
  {
    "id": "121",
    "order": 121,
    "slug": "calendar-input",
    "title": "Calendar Input",
    "description": "Input/form component: Calendar Input.",
    "category": "Components",
    "tags": [
      "calendar",
      "input",
      "docs",
      "inputs",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/calendar",
    "installCommand": ""
  },
  {
    "id": "122",
    "order": 122,
    "slug": "date-wheel-picker",
    "title": "Date Wheel Picker",
    "description": "Input/form component: Date Wheel Picker.",
    "category": "Components",
    "tags": [
      "date",
      "wheel",
      "picker",
      "docs",
      "inputs",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/date-wheel-picker",
    "installCommand": ""
  },
  {
    "id": "123",
    "order": 123,
    "slug": "feedback-widget",
    "title": "Feedback Widget",
    "description": "Input/form component: Feedback Widget.",
    "category": "Components",
    "tags": [
      "feedback",
      "widget",
      "docs",
      "inputs",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/feedback-widget",
    "installCommand": ""
  },
  {
    "id": "124",
    "order": 124,
    "slug": "file-tree",
    "title": "File Tree",
    "description": "Navigation component: File Tree.",
    "category": "Components",
    "tags": [
      "file",
      "tree",
      "docs",
      "navigation",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/navigation/file-tree",
    "installCommand": ""
  },
  {
    "id": "125",
    "order": 125,
    "slug": "animated-beam",
    "title": "Animated Beam",
    "description": "Animated Beam — a UI component reference from Joly UI.",
    "category": "Components",
    "tags": [
      "animated",
      "beam",
      "docs",
      "creative",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/animated-beam",
    "installCommand": ""
  },
  {
    "id": "126",
    "order": 126,
    "slug": "expanded-map",
    "title": "Expanded Map",
    "description": "Expanded Map — a UI component reference from Joly UI.",
    "category": "Components",
    "tags": [
      "expanded",
      "map",
      "docs",
      "creative",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/expanded-map",
    "installCommand": ""
  },
  {
    "id": "127",
    "order": 127,
    "slug": "github-star",
    "title": "Github Star",
    "description": "Github Star — a UI component reference from Joly UI.",
    "category": "Components",
    "tags": [
      "github",
      "star",
      "docs",
      "creative",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/github-star",
    "installCommand": ""
  },
  {
    "id": "128",
    "order": 128,
    "slug": "hover-preview",
    "title": "Hover Preview",
    "description": "Hover Preview — a UI component reference from Joly UI.",
    "category": "Components",
    "tags": [
      "hover",
      "preview",
      "docs",
      "creative",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/hover-preview",
    "installCommand": ""
  },
  {
    "id": "129",
    "order": 129,
    "slug": "image-sphere",
    "title": "Image Sphere",
    "description": "Image Sphere — a UI component reference from Joly UI.",
    "category": "Components",
    "tags": [
      "image",
      "sphere",
      "docs",
      "creative",
      "joly"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/image-sphere",
    "installCommand": ""
  },
  {
    "id": "130",
    "order": 130,
    "slug": "popover",
    "title": "Popover",
    "description": "Popover — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "popover",
      "docs",
      "radix",
      "animated"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/radix/popover",
    "installCommand": ""
  },
  {
    "id": "131",
    "order": 131,
    "slug": "progress",
    "title": "Progress",
    "description": "Progress — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "progress",
      "docs",
      "radix",
      "animated",
      "loading"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/radix/progress",
    "installCommand": ""
  },
  {
    "id": "132",
    "order": 132,
    "slug": "sheet",
    "title": "Sheet",
    "description": "Sheet — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "sheet",
      "docs",
      "radix",
      "animated"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/radix/sheet",
    "installCommand": ""
  },
  {
    "id": "133",
    "order": 133,
    "slug": "copy-button",
    "title": "Copy Button",
    "description": "Button/CTA component: Copy Button.",
    "category": "Components",
    "tags": [
      "copy",
      "button",
      "docs",
      "buttons",
      "animated",
      "cta"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/buttons/copy",
    "installCommand": ""
  },
  {
    "id": "134",
    "order": 134,
    "slug": "flip-button",
    "title": "Flip Button",
    "description": "Button/CTA component: Flip Button.",
    "category": "Components",
    "tags": [
      "flip",
      "button",
      "docs",
      "buttons",
      "animated",
      "cta"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/buttons/flip",
    "installCommand": ""
  },
  {
    "id": "135",
    "order": 135,
    "slug": "ripple-button",
    "title": "Ripple Button",
    "description": "Button/CTA component: Ripple Button.",
    "category": "Components",
    "tags": [
      "ripple",
      "button",
      "docs",
      "buttons",
      "animated",
      "cta"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/buttons/ripple",
    "installCommand": ""
  },
  {
    "id": "136",
    "order": 136,
    "slug": "hole-background",
    "title": "Hole Background",
    "description": "Animated background preset: Hole Background (drop into a section/hero).",
    "category": "Background",
    "tags": [
      "hole",
      "background",
      "docs",
      "backgrounds",
      "animated",
      "hero"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/backgrounds/hole",
    "installCommand": ""
  },
  {
    "id": "137",
    "order": 137,
    "slug": "flip-card",
    "title": "Flip Card",
    "description": "Flip Card — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "flip",
      "card",
      "docs",
      "community",
      "animated"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/community/flip-card",
    "installCommand": ""
  },
  {
    "id": "138",
    "order": 138,
    "slug": "management-bar",
    "title": "Management Bar",
    "description": "Management Bar — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "management",
      "bar",
      "docs",
      "community",
      "animated"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/community/management-bar",
    "installCommand": ""
  },
  {
    "id": "139",
    "order": 139,
    "slug": "motion-carousel",
    "title": "Motion Carousel",
    "description": "Motion Carousel — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "motion",
      "carousel",
      "docs",
      "community",
      "animated",
      "slider"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/community/motion-carousel",
    "installCommand": ""
  },
  {
    "id": "140",
    "order": 140,
    "slug": "playful-todolist",
    "title": "Playful TodoList",
    "description": "Playful TodoList — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "playful",
      "todolist",
      "docs",
      "community",
      "animated"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/community/playful-todolist",
    "installCommand": ""
  },
  {
    "id": "141",
    "order": 141,
    "slug": "radial-intro",
    "title": "Radial Intro",
    "description": "Radial Intro — a UI component reference from Animated UI.",
    "category": "Components",
    "tags": [
      "radial",
      "intro",
      "docs",
      "community",
      "animated"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/community/radial-intro",
    "installCommand": ""
  },
  {
    "id": "142",
    "order": 142,
    "slug": "radial-menu",
    "title": "Radial Menu",
    "description": "Navigation component: Radial Menu.",
    "category": "Components",
    "tags": [
      "radial",
      "menu",
      "docs",
      "community",
      "animated",
      "navigation"
    ],
    "library": "Animated UI",
    "docUrl": "https://animate-ui.com/docs/components/community/radial-menu",
    "installCommand": ""
  },
  {
    "id": "143",
    "order": 143,
    "slug": "icon-cloud",
    "title": "Icon Cloud",
    "description": "Icon Cloud — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "icons",
      "cloud",
      "canvas"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/icon-cloud",
    "installCommand": ""
  },
  {
    "id": "144",
    "order": 144,
    "slug": "border-beam",
    "title": "Border Beam",
    "description": "Border Beam — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "border",
      "beam",
      "card"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/border-beam",
    "installCommand": ""
  },
  {
    "id": "145",
    "order": 145,
    "slug": "shine-border",
    "title": "Shine Border",
    "description": "Shine Border — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "border",
      "shine",
      "card"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/shine-border",
    "installCommand": ""
  },
  {
    "id": "146",
    "order": 146,
    "slug": "magic-card",
    "title": "Magic Card",
    "description": "Magic Card — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "card",
      "hover",
      "gradient"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/magic-card",
    "installCommand": ""
  },
  {
    "id": "147",
    "order": 147,
    "slug": "compact-confetti",
    "title": "Compact Confetti",
    "description": "Compact Confetti — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "confetti",
      "celebration",
      "canvas"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/confetti",
    "installCommand": ""
  },
  {
    "id": "148",
    "order": 148,
    "slug": "video-text",
    "title": "Video Text",
    "description": "Video Text — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "video",
      "text",
      "docs",
      "magic"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/video-text",
    "installCommand": ""
  },
  {
    "id": "149",
    "order": 149,
    "slug": "text-reveal",
    "title": "Text Reveal",
    "description": "Text Reveal — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "text",
      "reveal",
      "docs",
      "magic"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/text-reveal",
    "installCommand": ""
  },
  {
    "id": "150",
    "order": 150,
    "slug": "sparkles-text",
    "title": "Sparkles Text",
    "description": "Sparkles Text — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "sparkles",
      "text",
      "docs",
      "magic"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/sparkles-text",
    "installCommand": ""
  },
  {
    "id": "151",
    "order": 151,
    "slug": "code-comparison",
    "title": "Code Comparison",
    "description": "Code Comparison — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "code",
      "comparison",
      "docs",
      "magic"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/code-comparison",
    "installCommand": ""
  },
  {
    "id": "152",
    "order": 152,
    "slug": "scroll-progress",
    "title": "Scroll Progress",
    "description": "Scroll Progress — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "scroll",
      "progress",
      "docs",
      "magic",
      "loading"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/scroll-progress",
    "installCommand": ""
  },
  {
    "id": "153",
    "order": 153,
    "slug": "neon-gradient-card",
    "title": "Neon Gradient Card",
    "description": "Neon Gradient Card — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "card",
      "neon",
      "gradient"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/neon-gradient-card",
    "installCommand": ""
  },
  {
    "id": "154",
    "order": 154,
    "slug": "circular-progress-bar",
    "title": "Circular Progress Bar",
    "description": "Circular Progress Bar — a UI component reference from Magic UI.",
    "category": "Components",
    "tags": [
      "circular",
      "progress",
      "bar",
      "docs",
      "animated",
      "magic",
      "loading"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/animated-circular-progress-bar",
    "installCommand": ""
  },
  {
    "id": "155",
    "order": 155,
    "slug": "draggable-card",
    "title": "Draggable Card",
    "description": "Draggable Card — a UI component reference from Aceternity UI.",
    "category": "Components",
    "tags": [
      "draggable",
      "card",
      "aceternity"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/draggable-card",
    "installCommand": ""
  },
  {
    "id": "156",
    "order": 156,
    "slug": "hero-parallax",
    "title": "Hero Parallax",
    "description": "Hero Parallax — a UI component reference from Aceternity UI.",
    "category": "Components",
    "tags": [
      "hero",
      "parallax",
      "aceternity"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/hero-parallax",
    "installCommand": ""
  },
  {
    "id": "157",
    "order": 157,
    "slug": "image-compare",
    "title": "Image Compare",
    "description": "Image Compare — a UI component reference from Aceternity UI.",
    "category": "Components",
    "tags": [
      "image",
      "compare",
      "aceternity"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/compare",
    "installCommand": ""
  },
  {
    "id": "158",
    "order": 158,
    "slug": "lens",
    "title": "Lens",
    "description": "Lens — a UI component reference from Aceternity UI.",
    "category": "Components",
    "tags": [
      "lens",
      "aceternity"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/lens",
    "installCommand": ""
  }
];
