// This file is auto-generated by scripts/generate-components.mjs
// Do not edit by hand.

export type ComponentRegistryItem = {
  id: string;
  order: number;
  slug: string;
  title: string;
  description: string;
  category: string;
  tags: string[];
  library: string;
  docUrl: string;
};

export const COMPONENTS: ComponentRegistryItem[] = [
  {
    "id": "1",
    "order": 1,
    "slug": "react-bits",
    "title": "React-Bits",
    "description": "React-Bits from React Bits.",
    "category": "Components",
    "tags": [],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/get-started/introduction"
  },
  {
    "id": "1",
    "order": 1,
    "slug": "split-text",
    "title": "Split Text",
    "description": "Split Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/split-text"
  },
  {
    "id": "2",
    "order": 2,
    "slug": "shadcn-io",
    "title": "Shadcn.io",
    "description": "Shadcn.io from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components"
  },
  {
    "id": "2",
    "order": 2,
    "slug": "circular-text",
    "title": "Circular Text",
    "description": "Circular Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/circular-text"
  },
  {
    "id": "3",
    "order": 3,
    "slug": "joly-ui",
    "title": "Joly UI",
    "description": "Joly UI from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/animated-beam"
  },
  {
    "id": "3",
    "order": 3,
    "slug": "shiny-text",
    "title": "Shiny Text",
    "description": "Shiny Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/shiny-text"
  },
  {
    "id": "4",
    "order": 4,
    "slug": "animated-ui",
    "title": "Animated UI",
    "description": "Animated UI from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components"
  },
  {
    "id": "4",
    "order": 4,
    "slug": "curved-marquee",
    "title": "Curved Marquee",
    "description": "Curved Marquee from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/curved-loop"
  },
  {
    "id": "5",
    "order": 5,
    "slug": "fuzzy-text",
    "title": "Fuzzy Text",
    "description": "Fuzzy Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/fuzzy-text"
  },
  {
    "id": "6",
    "order": 6,
    "slug": "gradient-text",
    "title": "Gradient Text",
    "description": "Gradient Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/gradient-text"
  },
  {
    "id": "7",
    "order": 7,
    "slug": "falling-text",
    "title": "Falling Text",
    "description": "Falling Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/falling-text"
  },
  {
    "id": "8",
    "order": 8,
    "slug": "text-cursor",
    "title": "Text Cursor",
    "description": "Text Cursor from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text",
      "cursor"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/text-cursor"
  },
  {
    "id": "9",
    "order": 9,
    "slug": "decrypted-text",
    "title": "Decrypted Text",
    "description": "Decrypted Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/decrypted-text"
  },
  {
    "id": "10",
    "order": 10,
    "slug": "scroll-float",
    "title": "Scroll Float",
    "description": "Scroll Float from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/scroll-float"
  },
  {
    "id": "11",
    "order": 11,
    "slug": "scroll-reveal",
    "title": "Scroll Reveal",
    "description": "Scroll Reveal from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/scroll-reveal"
  },
  {
    "id": "12",
    "order": 12,
    "slug": "rotating-text",
    "title": "Rotating Text",
    "description": "Rotating Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/rotating-text"
  },
  {
    "id": "13",
    "order": 13,
    "slug": "glitch-text",
    "title": "Glitch Text",
    "description": "Glitch Text from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations",
      "text"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/glitch-text"
  },
  {
    "id": "14",
    "order": 14,
    "slug": "scroll-velocity",
    "title": "Scroll Velocity",
    "description": "Scroll Velocity from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/scroll-velocity"
  },
  {
    "id": "15",
    "order": 15,
    "slug": "variable-proximity",
    "title": "Variable Proximity",
    "description": "Variable Proximity from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/variable-proximity"
  },
  {
    "id": "16",
    "order": 16,
    "slug": "count-up",
    "title": "Count Up",
    "description": "Count Up from React Bits.",
    "category": "Text",
    "tags": [
      "text-animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/text-animations/count-up"
  },
  {
    "id": "17",
    "order": 17,
    "slug": "electric-border",
    "title": "Electric Border",
    "description": "Electric Border from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/electric-border"
  },
  {
    "id": "18",
    "order": 18,
    "slug": "antigravity",
    "title": "Antigravity",
    "description": "Antigravity from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/antigravity"
  },
  {
    "id": "19",
    "order": 19,
    "slug": "logo-loop",
    "title": "Logo Loop",
    "description": "Logo Loop from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/logo-loop"
  },
  {
    "id": "20",
    "order": 20,
    "slug": "target-cursor",
    "title": "Target Cursor",
    "description": "Target Cursor from React Bits.",
    "category": "Animations",
    "tags": [
      "animations",
      "cursor"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/target-cursor"
  },
  {
    "id": "21",
    "order": 21,
    "slug": "laser-flow",
    "title": "Laser Flow",
    "description": "Laser Flow from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/laser-flow"
  },
  {
    "id": "22",
    "order": 22,
    "slug": "magnet-lines",
    "title": "Magnet Lines",
    "description": "Magnet Lines from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/magnet-lines"
  },
  {
    "id": "23",
    "order": 23,
    "slug": "ghost-cursor",
    "title": "Ghost Cursor",
    "description": "Ghost Cursor from React Bits.",
    "category": "Animations",
    "tags": [
      "animations",
      "cursor"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/ghost-cursor"
  },
  {
    "id": "24",
    "order": 24,
    "slug": "click-spark",
    "title": "Click Spark",
    "description": "Click Spark from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/click-spark"
  },
  {
    "id": "25",
    "order": 25,
    "slug": "sticker-peel",
    "title": "Sticker Peel",
    "description": "Sticker Peel from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/sticker-peel"
  },
  {
    "id": "26",
    "order": 26,
    "slug": "image-trail",
    "title": "Image Trail",
    "description": "Image Trail from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/image-trail"
  },
  {
    "id": "27",
    "order": 27,
    "slug": "splash-cursor",
    "title": "Splash Cursor",
    "description": "Splash Cursor from React Bits.",
    "category": "Animations",
    "tags": [
      "animations",
      "cursor"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/splash-cursor"
  },
  {
    "id": "28",
    "order": 28,
    "slug": "star-border",
    "title": "Star Border",
    "description": "Star Border from React Bits.",
    "category": "Animations",
    "tags": [
      "animations"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/animations/star-border"
  },
  {
    "id": "29",
    "order": 29,
    "slug": "animated-list",
    "title": "Animated List",
    "description": "Animated List from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/animated-list"
  },
  {
    "id": "30",
    "order": 30,
    "slug": "scroll-stack",
    "title": "Scroll Stack",
    "description": "Scroll Stack from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/scroll-stack"
  },
  {
    "id": "31",
    "order": 31,
    "slug": "magic-bento",
    "title": "Magic Bento",
    "description": "Magic Bento from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/magic-bento"
  },
  {
    "id": "32",
    "order": 32,
    "slug": "circular-gallery",
    "title": "Circular Gallery",
    "description": "Circular Gallery from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/circular-gallery"
  },
  {
    "id": "33",
    "order": 33,
    "slug": "image-stack",
    "title": "Image Stack",
    "description": "Image Stack from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/stack"
  },
  {
    "id": "34",
    "order": 34,
    "slug": "fluid-glass",
    "title": "Fluid Glass",
    "description": "Fluid Glass from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/fluid-glass"
  },
  {
    "id": "35",
    "order": 35,
    "slug": "masonry",
    "title": "Masonry",
    "description": "Masonry from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/masonry"
  },
  {
    "id": "36",
    "order": 36,
    "slug": "modal-viewer",
    "title": "Modal Viewer",
    "description": "Modal Viewer from React Bits.",
    "category": "Components",
    "tags": [
      "components",
      "overlay"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/model-viewer"
  },
  {
    "id": "37",
    "order": 37,
    "slug": "lanyard",
    "title": "Lanyard",
    "description": "Lanyard from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/lanyard"
  },
  {
    "id": "38",
    "order": 38,
    "slug": "dock",
    "title": "Dock",
    "description": "Dock from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/dock"
  },
  {
    "id": "39",
    "order": 39,
    "slug": "carousel",
    "title": "Carousel",
    "description": "Carousel from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/carousel"
  },
  {
    "id": "40",
    "order": 40,
    "slug": "spolight-card",
    "title": "Spolight Card",
    "description": "Spolight Card from React Bits.",
    "category": "Components",
    "tags": [
      "components",
      "card"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/spotlight-card"
  },
  {
    "id": "41",
    "order": 41,
    "slug": "flowing-menu",
    "title": "Flowing Menu",
    "description": "Flowing Menu from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/flowing-menu"
  },
  {
    "id": "42",
    "order": 42,
    "slug": "elastic-slider",
    "title": "Elastic Slider",
    "description": "Elastic Slider from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/elastic-slider"
  },
  {
    "id": "43",
    "order": 43,
    "slug": "counter",
    "title": "Counter",
    "description": "Counter from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/counter"
  },
  {
    "id": "44",
    "order": 44,
    "slug": "infinite-menu",
    "title": "Infinite Menu",
    "description": "Infinite Menu from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/infinite-menu"
  },
  {
    "id": "45",
    "order": 45,
    "slug": "stepper",
    "title": "Stepper",
    "description": "Stepper from React Bits.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/components/stepper"
  },
  {
    "id": "46",
    "order": 46,
    "slug": "liquid-ether",
    "title": "Liquid Ether",
    "description": "Liquid Ether from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/liquid-ether"
  },
  {
    "id": "47",
    "order": 47,
    "slug": "prism",
    "title": "Prism",
    "description": "Prism from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/prism"
  },
  {
    "id": "48",
    "order": 48,
    "slug": "dark-veil",
    "title": "Dark Veil",
    "description": "Dark Veil from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/dark-veil"
  },
  {
    "id": "49",
    "order": 49,
    "slug": "light-pillar",
    "title": "Light Pillar",
    "description": "Light Pillar from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/light-pillar"
  },
  {
    "id": "50",
    "order": 50,
    "slug": "floating-lines",
    "title": "Floating Lines",
    "description": "Floating Lines from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/floating-lines"
  },
  {
    "id": "51",
    "order": 51,
    "slug": "light-rays",
    "title": "Light Rays",
    "description": "Light Rays from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/light-rays"
  },
  {
    "id": "52",
    "order": 52,
    "slug": "color-bends",
    "title": "Color Bends",
    "description": "Color Bends from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/color-bends"
  },
  {
    "id": "53",
    "order": 53,
    "slug": "particles",
    "title": "Particles",
    "description": "Particles from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/particles"
  },
  {
    "id": "54",
    "order": 54,
    "slug": "grid-scan",
    "title": "Grid Scan",
    "description": "Grid Scan from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/grid-scan"
  },
  {
    "id": "55",
    "order": 55,
    "slug": "lightning",
    "title": "Lightning",
    "description": "Lightning from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/lightning"
  },
  {
    "id": "56",
    "order": 56,
    "slug": "galaxy",
    "title": "Galaxy",
    "description": "Galaxy from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/galaxy"
  },
  {
    "id": "57",
    "order": 57,
    "slug": "dot-grid",
    "title": "Dot Grid",
    "description": "Dot Grid from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/dot-grid"
  },
  {
    "id": "58",
    "order": 58,
    "slug": "hyperspeed",
    "title": "Hyperspeed",
    "description": "Hyperspeed from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/hyperspeed"
  },
  {
    "id": "59",
    "order": 59,
    "slug": "ballpit",
    "title": "Ballpit",
    "description": "Ballpit from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/ballpit"
  },
  {
    "id": "60",
    "order": 60,
    "slug": "orb",
    "title": "Orb",
    "description": "Orb from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/orb"
  },
  {
    "id": "61",
    "order": 61,
    "slug": "letter-glitch",
    "title": "Letter Glitch",
    "description": "Letter Glitch from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/letter-glitch"
  },
  {
    "id": "62",
    "order": 62,
    "slug": "grid-motion",
    "title": "Grid Motion",
    "description": "Grid Motion from React Bits.",
    "category": "Background",
    "tags": [
      "backgrounds"
    ],
    "library": "React Bits",
    "docUrl": "https://reactbits.dev/backgrounds/grid-motion"
  },
  {
    "id": "63",
    "order": 63,
    "slug": "code-block",
    "title": "Code Block",
    "description": "Code Block from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/code-block"
  },
  {
    "id": "64",
    "order": 64,
    "slug": "code-editor",
    "title": "Code Editor",
    "description": "Code Editor from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/code-editor"
  },
  {
    "id": "65",
    "order": 65,
    "slug": "code-tabs",
    "title": "Code Tabs",
    "description": "Code Tabs from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/code-tabs"
  },
  {
    "id": "66",
    "order": 66,
    "slug": "sandbox",
    "title": "Sandbox",
    "description": "Sandbox from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/sandbox"
  },
  {
    "id": "67",
    "order": 67,
    "slug": "ganttchart",
    "title": "GanttChart",
    "description": "GanttChart from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components",
      "chart"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/gantt"
  },
  {
    "id": "68",
    "order": 68,
    "slug": "kanban",
    "title": "Kanban",
    "description": "Kanban from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/kanban"
  },
  {
    "id": "69",
    "order": 69,
    "slug": "device-mock",
    "title": "Device Mock(Android)",
    "description": "Device Mock(Android) from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/android"
  },
  {
    "id": "70",
    "order": 70,
    "slug": "device-mock",
    "title": "Device Mock(IOS)",
    "description": "Device Mock(IOS) from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/iphone-15-pro"
  },
  {
    "id": "71",
    "order": 71,
    "slug": "macos-dock",
    "title": "MacOS Dock",
    "description": "MacOS Dock from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/mac-os-dock"
  },
  {
    "id": "72",
    "order": 72,
    "slug": "rating",
    "title": "Rating",
    "description": "Rating from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/rating"
  },
  {
    "id": "73",
    "order": 73,
    "slug": "credit-card",
    "title": "Credit Card",
    "description": "Credit Card from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components",
      "card"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/credit-card"
  },
  {
    "id": "74",
    "order": 74,
    "slug": "color-picker",
    "title": "Color Picker",
    "description": "Color Picker from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/color-picker"
  },
  {
    "id": "75",
    "order": 75,
    "slug": "combobox",
    "title": "Combobox",
    "description": "Combobox from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/combobox"
  },
  {
    "id": "76",
    "order": 76,
    "slug": "dropzone",
    "title": "Dropzone",
    "description": "Dropzone from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/dropzone"
  },
  {
    "id": "77",
    "order": 77,
    "slug": "image-zoom",
    "title": "Image Zoom",
    "description": "Image Zoom from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/image-zoom"
  },
  {
    "id": "78",
    "order": 78,
    "slug": "image-crop",
    "title": "Image Crop",
    "description": "Image Crop from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/image-crop"
  },
  {
    "id": "79",
    "order": 79,
    "slug": "3d-card",
    "title": "3D Card",
    "description": "3D Card from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components",
      "card"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/3d-card"
  },
  {
    "id": "80",
    "order": 80,
    "slug": "3d-marquee",
    "title": "3D Marquee",
    "description": "3D Marquee from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/3d-marquee"
  },
  {
    "id": "81",
    "order": 81,
    "slug": "animated-cursor",
    "title": "Animated Cursor",
    "description": "Animated Cursor from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components",
      "cursor"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/3d-marquee"
  },
  {
    "id": "82",
    "order": 82,
    "slug": "animated-testimonials",
    "title": "Animated Testimonials",
    "description": "Animated Testimonials from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/animated-testimonials"
  },
  {
    "id": "83",
    "order": 83,
    "slug": "animated-tooltip",
    "title": "Animated Tooltip",
    "description": "Animated Tooltip from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/animated-tooltip"
  },
  {
    "id": "84",
    "order": 84,
    "slug": "glimpse",
    "title": "Glimpse",
    "description": "Glimpse from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/glimpse"
  },
  {
    "id": "85",
    "order": 85,
    "slug": "pin-list",
    "title": "Pin List",
    "description": "Pin List from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/pin-list"
  },
  {
    "id": "86",
    "order": 86,
    "slug": "spinner",
    "title": "Spinner",
    "description": "Spinner from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/spinner"
  },
  {
    "id": "87",
    "order": 87,
    "slug": "tabs",
    "title": "Tabs",
    "description": "Tabs from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/tabs"
  },
  {
    "id": "88",
    "order": 88,
    "slug": "banner",
    "title": "Banner",
    "description": "Banner from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/banner"
  },
  {
    "id": "89",
    "order": 89,
    "slug": "marquee",
    "title": "Marquee",
    "description": "Marquee from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/marquee"
  },
  {
    "id": "90",
    "order": 90,
    "slug": "avatar-group",
    "title": "Avatar Group",
    "description": "Avatar Group from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/avatar-group"
  },
  {
    "id": "91",
    "order": 91,
    "slug": "tags",
    "title": "Tags",
    "description": "Tags from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/tags"
  },
  {
    "id": "92",
    "order": 92,
    "slug": "calendar",
    "title": "Calendar",
    "description": "Calendar from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/calendar"
  },
  {
    "id": "93",
    "order": 93,
    "slug": "mini-calendar",
    "title": "Mini Calendar",
    "description": "Mini Calendar from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/mini-calendar"
  },
  {
    "id": "94",
    "order": 94,
    "slug": "comparison-slider",
    "title": "Comparison Slider",
    "description": "Comparison Slider from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/comparison"
  },
  {
    "id": "95",
    "order": 95,
    "slug": "kbd",
    "title": "KBD",
    "description": "KBD from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/kbd"
  },
  {
    "id": "96",
    "order": 96,
    "slug": "qr-code",
    "title": "Qr Code",
    "description": "Qr Code from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/qr-code"
  },
  {
    "id": "97",
    "order": 97,
    "slug": "status",
    "title": "Status",
    "description": "Status from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/status"
  },
  {
    "id": "98",
    "order": 98,
    "slug": "terminal",
    "title": "Terminal",
    "description": "Terminal from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/terminal"
  },
  {
    "id": "99",
    "order": 99,
    "slug": "video-player",
    "title": "Video Player",
    "description": "Video Player from shadcn/ui.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/components/video-player"
  },
  {
    "id": "100",
    "order": 100,
    "slug": "beam-collision",
    "title": "Beam Collision",
    "description": "Beam Collision from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/beams-collision"
  },
  {
    "id": "101",
    "order": 101,
    "slug": "confetti",
    "title": "Confetti",
    "description": "Confetti from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/confetti"
  },
  {
    "id": "102",
    "order": 102,
    "slug": "fireworks",
    "title": "Fireworks",
    "description": "Fireworks from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/fireworks"
  },
  {
    "id": "103",
    "order": 103,
    "slug": "meteors",
    "title": "Meteors",
    "description": "Meteors from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/fireworks"
  },
  {
    "id": "104",
    "order": 104,
    "slug": "orbits",
    "title": "Orbits",
    "description": "Orbits from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/fireworks"
  },
  {
    "id": "105",
    "order": 105,
    "slug": "rain",
    "title": "Rain",
    "description": "Rain from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/rain"
  },
  {
    "id": "106",
    "order": 106,
    "slug": "snow",
    "title": "Snow",
    "description": "Snow from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/snow"
  },
  {
    "id": "107",
    "order": 107,
    "slug": "vortex",
    "title": "Vortex",
    "description": "Vortex from shadcn/ui.",
    "category": "Background",
    "tags": [],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/background/vortex"
  },
  {
    "id": "108",
    "order": 108,
    "slug": "gradient-area-chart",
    "title": "Gradient Area Chart",
    "description": "Gradient Area Chart from shadcn/ui.",
    "category": "Charts",
    "tags": [
      "charts",
      "chart"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/charts/area-gradient"
  },
  {
    "id": "109",
    "order": 109,
    "slug": "horizontal-bar",
    "title": "Horizontal Bar",
    "description": "Horizontal Bar from shadcn/ui.",
    "category": "Charts",
    "tags": [
      "charts"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/charts/bar-horizontal"
  },
  {
    "id": "110",
    "order": 110,
    "slug": "interactive-bar",
    "title": "Interactive Bar",
    "description": "Interactive Bar from shadcn/ui.",
    "category": "Charts",
    "tags": [
      "charts"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/charts/bar-interactive"
  },
  {
    "id": "111",
    "order": 111,
    "slug": "pie-donut",
    "title": "Pie Donut",
    "description": "Pie Donut from shadcn/ui.",
    "category": "Charts",
    "tags": [
      "charts"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/charts/pie-donut"
  },
  {
    "id": "112",
    "order": 112,
    "slug": "radar-chart",
    "title": "Radar Chart",
    "description": "Radar Chart from shadcn/ui.",
    "category": "Charts",
    "tags": [
      "charts",
      "chart"
    ],
    "library": "shadcn/ui",
    "docUrl": "https://www.shadcn.io/charts/radar-dots"
  },
  {
    "id": "113",
    "order": 113,
    "slug": "rainbow-button",
    "title": "Rainbow button",
    "description": "Rainbow button from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/buttons/rainbow-button"
  },
  {
    "id": "114",
    "order": 114,
    "slug": "gooey-text-morphing",
    "title": "Gooey Text Morphing",
    "description": "Gooey Text Morphing from Joly UI.",
    "category": "Text",
    "tags": [
      "docs",
      "components",
      "text-animations",
      "text"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/gooey-text-morphing"
  },
  {
    "id": "115",
    "order": 115,
    "slug": "highlight-text",
    "title": "Highlight Text",
    "description": "Highlight Text from Joly UI.",
    "category": "Text",
    "tags": [
      "docs",
      "components",
      "text-animations",
      "text"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/highlight-text"
  },
  {
    "id": "116",
    "order": 116,
    "slug": "number-counter",
    "title": "Number Counter",
    "description": "Number Counter from Joly UI.",
    "category": "Text",
    "tags": [
      "docs",
      "components",
      "text-animations"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/number-counter"
  },
  {
    "id": "117",
    "order": 117,
    "slug": "rotate-text",
    "title": "Rotate Text",
    "description": "Rotate Text from Joly UI.",
    "category": "Text",
    "tags": [
      "docs",
      "components",
      "text-animations",
      "text"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/rotate-text"
  },
  {
    "id": "118",
    "order": 118,
    "slug": "typewriter-text",
    "title": "Typewriter Text",
    "description": "Typewriter Text from Joly UI.",
    "category": "Text",
    "tags": [
      "docs",
      "components",
      "text-animations",
      "text"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/text-animations/typewritter-text"
  },
  {
    "id": "119",
    "order": 119,
    "slug": "ai-prompt-box",
    "title": "AI prompt box",
    "description": "AI prompt box from Joly UI.",
    "category": "Inputs",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/ai-prompt-box"
  },
  {
    "id": "120",
    "order": 120,
    "slug": "animated-theme-toggle",
    "title": "Animated Theme Toggle",
    "description": "Animated Theme Toggle from Joly UI.",
    "category": "Inputs",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/animated-theme-toggle"
  },
  {
    "id": "121",
    "order": 121,
    "slug": "calendar-inout",
    "title": "Calendar Inout",
    "description": "Calendar Inout from Joly UI.",
    "category": "Inputs",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/calendar"
  },
  {
    "id": "122",
    "order": 122,
    "slug": "date-wheel-picker",
    "title": "Date Wheel Picker",
    "description": "Date Wheel Picker from Joly UI.",
    "category": "Inputs",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/date-wheel-picker"
  },
  {
    "id": "123",
    "order": 123,
    "slug": "feedback-widget",
    "title": "Feedback Widget",
    "description": "Feedback Widget from Joly UI.",
    "category": "Inputs",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/inputs/feedback-widget"
  },
  {
    "id": "124",
    "order": 124,
    "slug": "file-tree",
    "title": "File Tree",
    "description": "File Tree from Joly UI.",
    "category": "Navigation",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/navigation/file-tree"
  },
  {
    "id": "125",
    "order": 125,
    "slug": "animated-beam",
    "title": "Animated Beam",
    "description": "Animated Beam from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/animated-beam"
  },
  {
    "id": "126",
    "order": 126,
    "slug": "expanded-map",
    "title": "Expanded Map",
    "description": "Expanded Map from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/expanded-map"
  },
  {
    "id": "127",
    "order": 127,
    "slug": "github-star",
    "title": "Github Star",
    "description": "Github Star from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/github-star"
  },
  {
    "id": "128",
    "order": 128,
    "slug": "hover-preview",
    "title": "Hover Preview",
    "description": "Hover Preview from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/hover-preview"
  },
  {
    "id": "129",
    "order": 129,
    "slug": "image-sphere",
    "title": "Image Sphere",
    "description": "Image Sphere from Joly UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Joly UI",
    "docUrl": "https://www.jolyui.dev/docs/components/creative/image-sphere"
  },
  {
    "id": "130",
    "order": 130,
    "slug": "popover",
    "title": "Popover",
    "description": "Popover from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "radix",
      "overlay"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/radix/popover"
  },
  {
    "id": "131",
    "order": 131,
    "slug": "progress",
    "title": "Progress",
    "description": "Progress from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "radix"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/radix/progress"
  },
  {
    "id": "132",
    "order": 132,
    "slug": "sheet",
    "title": "Sheet",
    "description": "Sheet from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "radix",
      "overlay"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/radix/sheet"
  },
  {
    "id": "133",
    "order": 133,
    "slug": "copy-button",
    "title": "Copy Button",
    "description": "Copy Button from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/buttons/copy"
  },
  {
    "id": "134",
    "order": 134,
    "slug": "flip-button",
    "title": "Flip Button",
    "description": "Flip Button from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/buttons/flip"
  },
  {
    "id": "135",
    "order": 135,
    "slug": "ripple-button",
    "title": "Ripple Button",
    "description": "Ripple Button from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/buttons/ripple"
  },
  {
    "id": "136",
    "order": 136,
    "slug": "hole-backgrond",
    "title": "Hole Backgrond",
    "description": "Hole Backgrond from Animate UI.",
    "category": "Background",
    "tags": [
      "docs",
      "components",
      "backgrounds"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/backgrounds/hole"
  },
  {
    "id": "137",
    "order": 137,
    "slug": "flip-card",
    "title": "Flip Card",
    "description": "Flip Card from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "community",
      "card"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/community/flip-card"
  },
  {
    "id": "138",
    "order": 138,
    "slug": "management-bar",
    "title": "Management Bar",
    "description": "Management Bar from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "community"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/community/management-bar"
  },
  {
    "id": "139",
    "order": 139,
    "slug": "motion-carousel",
    "title": "Motion Carousel",
    "description": "Motion Carousel from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "community"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/community/motion-carousel"
  },
  {
    "id": "140",
    "order": 140,
    "slug": "playful-todolist",
    "title": "Playful TodoList",
    "description": "Playful TodoList from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "community"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/community/playful-todolist"
  },
  {
    "id": "141",
    "order": 141,
    "slug": "radial-intro",
    "title": "Radial Intro",
    "description": "Radial Intro from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "community"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/community/radial-intro"
  },
  {
    "id": "142",
    "order": 142,
    "slug": "radial-menu",
    "title": "Radial Menu",
    "description": "Radial Menu from Animate UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "community"
    ],
    "library": "Animate UI",
    "docUrl": "https://animate-ui.com/docs/components/community/radial-menu"
  },
  {
    "id": "143",
    "order": 143,
    "slug": "icon-cloud",
    "title": "Icon Cloud",
    "description": "Icon Cloud from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/icon-cloud"
  },
  {
    "id": "144",
    "order": 144,
    "slug": "border-beam",
    "title": "Border Beam",
    "description": "Border Beam from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/border-beam"
  },
  {
    "id": "145",
    "order": 145,
    "slug": "shine-border",
    "title": "Shine Border",
    "description": "Shine Border from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/shine-border"
  },
  {
    "id": "146",
    "order": 146,
    "slug": "magic-card",
    "title": "Magic Card",
    "description": "Magic Card from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "card"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/magic-card"
  },
  {
    "id": "147",
    "order": 147,
    "slug": "compact-confetti",
    "title": "Compact Confetti",
    "description": "Compact Confetti from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/confetti"
  },
  {
    "id": "148",
    "order": 148,
    "slug": "video-text",
    "title": "Video Text",
    "description": "Video Text from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "text"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/video-text"
  },
  {
    "id": "149",
    "order": 149,
    "slug": "text-reveal",
    "title": "Text Reveal",
    "description": "Text Reveal from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "text"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/text-reveal"
  },
  {
    "id": "150",
    "order": 150,
    "slug": "sparkles-text",
    "title": "Sparkles Text",
    "description": "Sparkles Text from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "text"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/sparkles-text"
  },
  {
    "id": "151",
    "order": 151,
    "slug": "code-comparison",
    "title": "Code Comparison",
    "description": "Code Comparison from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/code-comparison"
  },
  {
    "id": "152",
    "order": 152,
    "slug": "scroll-progress",
    "title": "Scroll Progress",
    "description": "Scroll Progress from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/scroll-progress"
  },
  {
    "id": "153",
    "order": 153,
    "slug": "neon-gradient-card",
    "title": "Neon Gradient Card",
    "description": "Neon Gradient Card from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components",
      "card"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/neon-gradient-card"
  },
  {
    "id": "154",
    "order": 154,
    "slug": "circular-progress-bar",
    "title": "Circular Progress Bar",
    "description": "Circular Progress Bar from Magic UI.",
    "category": "Components",
    "tags": [
      "docs",
      "components"
    ],
    "library": "Magic UI",
    "docUrl": "https://magicui.design/docs/components/animated-circular-progress-bar"
  },
  {
    "id": "155",
    "order": 155,
    "slug": "draggable-card",
    "title": "Draggable Card",
    "description": "Draggable Card from Aceternity UI.",
    "category": "Components",
    "tags": [
      "components",
      "card"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/draggable-card"
  },
  {
    "id": "156",
    "order": 156,
    "slug": "hero-parallax",
    "title": "Hero Parallax",
    "description": "Hero Parallax from Aceternity UI.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/hero-parallax"
  },
  {
    "id": "157",
    "order": 157,
    "slug": "image-compare",
    "title": "Image Compare",
    "description": "Image Compare from Aceternity UI.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/compare"
  },
  {
    "id": "158",
    "order": 158,
    "slug": "lens",
    "title": "Lens",
    "description": "Lens from Aceternity UI.",
    "category": "Components",
    "tags": [
      "components"
    ],
    "library": "Aceternity UI",
    "docUrl": "https://ui.aceternity.com/components/lens"
  }
] as const;
